#!/bin/bash
# Builds PersonaBot.app and installs it to ~/Applications.
#
# A GUI-launched .app gets a minimal PATH (no .zshrc/.zprofile), so the
# launcher needs an absolute python3 path baked in at build time — this
# script finds whichever python3 actually has the project's dependencies
# installed and hardcodes that, rather than relying on `python3` resolving
# correctly at launch time.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP="$HOME/Applications/PersonaBot.app"
PORT=8000
# Share links from other devices need the server on all interfaces:
#   PERSONABOT_HOST=0.0.0.0 bash macapp/build.sh
# The default keeps personabot reachable from this Mac only.
HOST="${PERSONABOT_HOST:-127.0.0.1}"

echo "Finding a python3 with this project's dependencies..."
PYTHON=""
for candidate in python3 /Library/Frameworks/Python.framework/Versions/3.11/bin/python3 /opt/homebrew/bin/python3 /usr/local/bin/python3; do
  if command -v "$candidate" >/dev/null 2>&1; then
    resolved="$(command -v "$candidate")"
    if "$resolved" -c "import mlx, mlx_lm, fastapi" >/dev/null 2>&1; then
      PYTHON="$resolved"
      break
    fi
  fi
done
if [ -z "$PYTHON" ]; then
  echo "No python3 found with mlx/mlx_lm/fastapi installed." >&2
  echo "Run: pip install -r requirements.txt   (from $REPO_DIR)" >&2
  exit 1
fi
echo "Using $PYTHON"

mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>
    <string>PersonaBot</string>
    <key>CFBundleIdentifier</key>
    <string>com.personabot.app</string>
    <key>CFBundleName</key>
    <string>PersonaBot</string>
    <key>CFBundleDisplayName</key>
    <string>PersonaBot</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0</string>
    <key>CFBundleVersion</key>
    <string>1</string>
    <key>CFBundleIconFile</key>
    <string>AppIcon.icns</string>
    <key>LSMinimumSystemVersion</key>
    <string>12.0</string>
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>LSApplicationCategoryType</key>
    <string>public.app-category.utilities</string>
</dict>
</plist>
PLIST

cat > "$APP/Contents/MacOS/PersonaBot" <<LAUNCHER
#!/bin/bash
# Generated by macapp/build.sh — edit that script, not this file.
APP_DIR="$REPO_DIR"
PORT=$PORT
HOST="$HOST"
PYTHON="$PYTHON"
LOG="/tmp/personabot_server.log"

if ! curl -s --max-time 2 "http://localhost:\$PORT/api/personas" >/dev/null 2>&1; then
  if [ ! -d "\$APP_DIR/backend" ]; then
    osascript -e "display alert \\"PersonaBot\\" message \\"Could not find \$APP_DIR/backend.\\" as critical"
    exit 1
  fi
  cd "\$APP_DIR/backend" || exit 1
  nohup "\$PYTHON" -m uvicorn app:app --host "\$HOST" --port "\$PORT" > "\$LOG" 2>&1 &
  disown

  ok=0
  for i in \$(seq 1 30); do
    if curl -s --max-time 1 "http://localhost:\$PORT/api/personas" >/dev/null 2>&1; then
      ok=1
      break
    fi
    sleep 0.5
  done

  if [ "\$ok" -eq 0 ]; then
    osascript -e "display alert \\"PersonaBot\\" message \\"Server didn't start in time. Check \$LOG for errors.\\" as critical"
    exit 1
  fi
fi

open "http://localhost:\$PORT"
LAUNCHER
chmod +x "$APP/Contents/MacOS/PersonaBot"

echo "Building icon..."
"$PYTHON" "$REPO_DIR/macapp/make_icon.py" "$APP/Contents/Resources" \
  || echo "Icon build failed (pip install pillow?) — app will use a generic icon."

touch "$APP"
echo "Installed $APP"
echo "Find it in ~/Applications or Spotlight ('PersonaBot')."
